[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  node_bundler = "esbuild"

# Optional: keep nice URLs
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

